version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable all pull requests for GitHub Actions dependencies
    open-pull-requests-limit: 0

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/11.20/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/12.15/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/13.11/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/14.8/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/15.2/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]
