version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable all pull requests for GitHub Actions dependencies
    open-pull-requests-limit: 0

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/12.19/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/13.15/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/14.12/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/15.6/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/16.2/debian/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postgres"
        update-types: [ "version-update:semver-major" ]
