name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '10.20/**'
      - '11.15/**'
      - '12.9/**'
      - '13.5/**'
      - '14.1/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [10.20, 11.15, 12.9, 13.5, 14.1]
        include:
          - version: 10.20
            docker-context: 10.20/debian/default
            docker-tags: |
              nicoherbigde/postgresql:10.20
              nicoherbigio/postgresql:10.20
          - version: 11.15
            docker-context: 11.15/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.15
              nicoherbigio/postgresql:11.15
          - version: 12.9
            docker-context: 12.9/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.9
              nicoherbigio/postgresql:12.9
          - version: 13.5
            docker-context: 13.5/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.5
              nicoherbigio/postgresql:13.5
          - version: 14.1
            docker-context: 14.1/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.1
              nicoherbigio/postgresql:14.1

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
