name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '11.19/**'
      - '12.13/**'
      - '13.9/**'
      - '14.6/**'
      - '15.1/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [11.19-bullseye, 12.13-bullseye, 13.9-bullseye, 14.6-bullseye, 15.1-bullseye]
        include:
          - version: 11.19-bullseye
            docker-context: 11.19/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.19
              nicoherbigde/postgresql:11.19-bullseye
          - version: 12.13-bullseye
            docker-context: 12.13/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.13
              nicoherbigde/postgresql:12.13-bullseye
          - version: 13.9-bullseye
            docker-context: 13.9/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.9
              nicoherbigde/postgresql:13.9-bullseye
          - version: 14.6-bullseye
            docker-context: 14.6/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.6
              nicoherbigde/postgresql:14.6-bullseye
          - version: 15.1-bullseye
            docker-context: 15.1/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.1
              nicoherbigde/postgresql:15.1-bullseye

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
