name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '11.21/**'
      - '12.16/**'
      - '13.12/**'
      - '14.9/**'
      - '15.3/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [11.21-bullseye, 12.16-bullseye, 13.12-bullseye, 14.9-bullseye, 15.3-bullseye]
        include:
          - version: 11.21-bullseye
            docker-context: 11.21/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.21
              nicoherbigde/postgresql:11.21-bullseye
          - version: 12.16-bullseye
            docker-context: 12.16/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.16
              nicoherbigde/postgresql:12.16-bullseye
          - version: 13.11-bullseye
            docker-context: 13.11/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.12
              nicoherbigde/postgresql:13.12-bullseye
          - version: 14.9-bullseye
            docker-context: 14.9/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.9
              nicoherbigde/postgresql:14.9-bullseye
          - version: 15.3-bullseye
            docker-context: 15.3/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.3
              nicoherbigde/postgresql:15.3-bullseye

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
