name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '13.19/**'
      - '14.16/**'
      - '15.11/**'
      - '16.7/**'
      - '17.2/**'
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-24.04]

    strategy:
      fail-fast: false
      matrix:
        version: [13.19-bookworm, 14.16-bookworm, 15.11-bookworm, 16.7-bookworm, 17.2-bookworm]
        include:
          - version: 13.19-bookworm
            docker-context: 13.19/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.19
              nicoherbigde/postgresql:13.19-bookworm
          - version: 14.16-bookworm
            docker-context: 14.16/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.16
              nicoherbigde/postgresql:14.16-bookworm
          - version: 15.11-bookworm
            docker-context: 15.11/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.11
              nicoherbigde/postgresql:15.11-bookworm
          - version: 16.7-bookworm
            docker-context: 16.7/debian/default
            docker-tags: |
              nicoherbigde/postgresql:16.7
              nicoherbigde/postgresql:16.7-bookworm
          - version: 17.2-bookworm
            docker-context: 17.2/debian/default
            docker-tags: |
              nicoherbigde/postgresql:17.2
              nicoherbigde/postgresql:17.2-bookworm

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
