name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '11.20/**'
      - '12.14/**'
      - '13.11/**'
      - '14.7/**'
      - '15.2/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [11.20-bullseye, 12.14-bullseye, 13.11-bullseye, 14.7-bullseye, 15.2-bullseye]
        include:
          - version: 11.20-bullseye
            docker-context: 11.20/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.20
              nicoherbigde/postgresql:11.20-bullseye
          - version: 12.14-bullseye
            docker-context: 12.14/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.14
              nicoherbigde/postgresql:12.14-bullseye
          - version: 13.11-bullseye
            docker-context: 13.11/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.11
              nicoherbigde/postgresql:13.11-bullseye
          - version: 14.7-bullseye
            docker-context: 14.7/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.7
              nicoherbigde/postgresql:14.7-bullseye
          - version: 15.2-bullseye
            docker-context: 15.2/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.2
              nicoherbigde/postgresql:15.2-bullseye

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
