name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '10.22/**'
      - '11.17/**'
      - '12.12/**'
      - '13.7/**'
      - '14.4/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [10.22, 11.17, 12.12, 13.7, 14.4]
        include:
          - version: 10.22
            docker-context: 10.22/debian/default
            docker-tags: |
              nicoherbigde/postgresql:10.22
              nicoherbigio/postgresql:10.22
          - version: 11.17
            docker-context: 11.17/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.17
              nicoherbigio/postgresql:11.17
          - version: 12.12
            docker-context: 12.12/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.12
              nicoherbigio/postgresql:12.12
          - version: 13.7
            docker-context: 13.7/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.7
              nicoherbigio/postgresql:13.7
          - version: 14.4
            docker-context: 14.4/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.4
              nicoherbigio/postgresql:14.4

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
