name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '11.22/**'
      - '12.17/**'
      - '13.13/**'
      - '14.10/**'
      - '15.5/**'
      - '16.0/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [11.22-bullseye, 12.17-bullseye, 13.13-bullseye, 14.10-bullseye, 15.5-bullseye, 16.0-bullseye]
        include:
          - version: 11.22-bullseye
            docker-context: 11.22/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.22
              nicoherbigde/postgresql:11.22-bullseye
          - version: 12.17-bullseye
            docker-context: 12.17/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.17
              nicoherbigde/postgresql:12.17-bullseye
          - version: 13.13-bullseye
            docker-context: 13.13/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.13
              nicoherbigde/postgresql:13.13-bullseye
          - version: 14.10-bullseye
            docker-context: 14.10/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.10
              nicoherbigde/postgresql:14.10-bullseye
          - version: 15.5-bullseye
            docker-context: 15.5/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.5
              nicoherbigde/postgresql:15.5-bullseye
          - version: 16.0-bullseye
            docker-context: 16.0/debian/default
            docker-tags: |
              nicoherbigde/postgresql:16.0
              nicoherbigde/postgresql:16.0-bullseye

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
