name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '10.21/**'
      - '11.16/**'
      - '12.11/**'
      - '13.7/**'
      - '14.2/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [10.21, 11.16, 12.11, 13.7, 14.2]
        include:
          - version: 10.21
            docker-context: 10.21/debian/default
            docker-tags: |
              nicoherbigde/postgresql:10.21
              nicoherbigio/postgresql:10.21
          - version: 11.16
            docker-context: 11.16/debian/default
            docker-tags: |
              nicoherbigde/postgresql:11.16
              nicoherbigio/postgresql:11.16
          - version: 12.11
            docker-context: 12.11/debian/default
            docker-tags: |
              nicoherbigde/postgresql:12.11
              nicoherbigio/postgresql:12.11
          - version: 13.7
            docker-context: 13.7/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.7
              nicoherbigio/postgresql:13.7
          - version: 14.2
            docker-context: 14.2/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.2
              nicoherbigio/postgresql:14.2

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
