name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '13.17/**'
      - '14.14/**'
      - '15.9/**'
      - '16.4/**'
      - '17.0/**'
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-24.04]

    strategy:
      fail-fast: false
      matrix:
        version: [13.17-bookworm, 14.14-bookworm, 15.9-bookworm, 16.4-bookworm, 17.0-bookworm]
        include:
          - version: 13.17-bookworm
            docker-context: 13.17/debian/default
            docker-tags: |
              nicoherbigde/postgresql:13.17
              nicoherbigde/postgresql:13.17-bookworm
          - version: 14.14-bookworm
            docker-context: 14.14/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.14
              nicoherbigde/postgresql:14.14-bookworm
          - version: 15.9-bookworm
            docker-context: 15.9/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.9
              nicoherbigde/postgresql:15.9-bookworm
          - version: 16.4-bookworm
            docker-context: 16.4/debian/default
            docker-tags: |
              nicoherbigde/postgresql:16.4
              nicoherbigde/postgresql:16.4-bookworm
          - version: 17.0-bookworm
            docker-context: 17.0/debian/default
            docker-tags: |
              nicoherbigde/postgresql:17.0
              nicoherbigde/postgresql:17.0-bookworm

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
